"""Fix ExchangeStatus Enum issue

Revision ID: 0b6caeb10647
Revises: 67a338a0fe6d
Create Date: 2024-10-27 22:09:15.004771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6caeb10647'
down_revision: Union[str, None] = '67a338a0fe6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
